ALTER TABLE modalities
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('modalities', 'id'),
    COALESCE((SELECT MAX(id) FROM modalities), 0) + 1,
    FALSE
);

CREATE UNIQUE INDEX uk_modalities_name_case_insensitive
    ON modalities (lower(name));
